=== AnneMund/HELM2NotationToolkit/src/main/resources/org/helm/notation2/resources/NucleotideTemplateSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="lmr" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:lmr="lmr">
    <element name="NUCLEOTIDE_TEMPLATES" type="lmr:TEMPLATE_LIST_TYPE"/>
    <complexType name="TEMPLATE_LIST_TYPE">
        <sequence>
            <element name="TEMPLATE" type="lmr:TEMPLATE_TYPE" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    <complexType name="TEMPLATE_TYPE">
        <sequence>
            <element name="NUCLEOTIDE" type="lmr:NUCLEOTIDE_TYPE" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="notationSource" type="lmr:SHORT_STRING_TYPE"/>
    </complexType>
    <complexType name="NUCLEOTIDE_TYPE">
        <sequence>
            <element name="SYMBOL" type="lmr:SHORT_STRING_TYPE" />
            <element name="MONOMER_NOTATION" type="lmr:SHORT_STRING_TYPE" />
        </sequence>
    </complexType>
    <simpleType name="SHORT_STRING_TYPE">
        <restriction base="string">
            <maxLength value="50"/>
        </restriction>
    </simpleType>
</schema>

=== AnneMund/HELM2NotationToolkit/src/main/resources/org/helm/notation/resources/NucleotideTemplates.xml
<?xml version="1.0" encoding="UTF-8"?>
<NUCLEOTIDE_TEMPLATES xsi:schemaLocation="lmr NucleotideTemplateSchema.xsd" xmlns="lmr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <TEMPLATE notationSource="HELM Notation" >
        <NUCLEOTIDE>
            <SYMBOL>A</SYMBOL>
            <MONOMER_NOTATION>R(A)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>U</SYMBOL>
            <MONOMER_NOTATION>R(U)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>G</SYMBOL>
            <MONOMER_NOTATION>R(G)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>C</SYMBOL>
            <MONOMER_NOTATION>R(C)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>T</SYMBOL>
            <MONOMER_NOTATION>R(T)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>mA</SYMBOL>
            <MONOMER_NOTATION>[mR](A)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>mU</SYMBOL>
            <MONOMER_NOTATION>[mR](U)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>mG</SYMBOL>
            <MONOMER_NOTATION>[mR](G)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>mC</SYMBOL>
            <MONOMER_NOTATION>[mR](C)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>mT</SYMBOL>
            <MONOMER_NOTATION>[mR](T)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>dA</SYMBOL>
            <MONOMER_NOTATION>[dR](A)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>dU</SYMBOL>
            <MONOMER_NOTATION>[dR](U)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>dG</SYMBOL>
            <MONOMER_NOTATION>[dR](G)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>dC</SYMBOL>
            <MONOMER_NOTATION>[dR](C)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>dT</SYMBOL>
            <MONOMER_NOTATION>[dR](T)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>fA</SYMBOL>
            <MONOMER_NOTATION>[fR](A)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>fU</SYMBOL>
            <MONOMER_NOTATION>[fR](U)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>fG</SYMBOL>
            <MONOMER_NOTATION>[fR](G)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>fC</SYMBOL>
            <MONOMER_NOTATION>[fR](C)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
        <NUCLEOTIDE>
            <SYMBOL>fT</SYMBOL>
            <MONOMER_NOTATION>[fR](T)P</MONOMER_NOTATION>
        </NUCLEOTIDE>
    </TEMPLATE>
</NUCLEOTIDE_TEMPLATES>
